spring.application.name=reporte
server.port=8094
spring.datasource.url=jdbc:mysql://localhost:3306/db_reportes
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
logging.level.com.urbano=DEBUG
